### ISSUE TITLE
Page Navigation

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/ProfPractice#4]
Sidebar menu
Create an array variable which lists 4 objects in app.component.ts
 public appMenu = [
    { title: "Home", url: '/home', icon: 'home', pathMatch: 'full' },
    { title: "Plan a Journey", url: '/journey-planner', icon: 'add', pathMatch: 'full' },
    { title: "Map", url: '/map', icon: 'map', pathMatch: 'full' },
    { title: "Login/Register", url: '/login', icon: 'happy', pathMatch: 'full' },
    { title: "Manage Journies", url: '/database', icon: 'trash', pathMatch: 'full' }
  ]
2.	in app.component.html
    
  <ion-app>
    <ion-split-pane>  split-pane displays two components, either side by side or one on top of the othe
      <ion-menu type="overlay"> "backdrop" effect
        <ion-header>
  	<ion-toolbar>
  	  <ion-title>
  	    Menu
  	  </ion-title>
  	</ion-toolbar>
        </ion-header>
        <ion-content>
  	<ion-list>
  	  <ion-menu-toggle auto-hide="false" *ngFor="let p of appMenu">  each element p of appMenu[] declared in app.component.ts
  	    <ion-item [routerDirection]="'root'" [routerLink]="[p.url]">
  	      <ion-icon slot="start" [name]="p.icon"></ion-icon>
  	      <ion-label>{{p.title}} </ion-label>
  	    </ion-item>
  	  </ion-menu-toggle>
  	</ion-list>
        </ion-content>
      </ion-menu>

  <ion-router-outlet main></ion-router-outlet>
</ion-split-pane>
</ion-app>
As when the application starts it automatically goes to home page, as it can be seen from app-routing.module.ts the following code needs to be added to home.page.html
	<ion-header>
	  <ion-toolbar>
	    <ion-buttons slot="start"> shift all buttons to the left
	      <ion-menu-button></ion-menu-button> "hamburger button"
	    </ion-buttons>
	    <ion-title>
	      Going My Way/RideShare
	    </ion-title>
	  </ion-toolbar>
	</ion-header>

**Comment by makarenkoelena** [comment]
Create an array variable which lists 4 objects in app.component.ts
 public appMenu = [
    { title: "Home", url: '/home', icon: 'home', pathMatch: 'full' },
    { title: "Plan a Journey", url: '/journey-planner', icon: 'add', pathMatch: 'full' },
    { title: "Map", url: '/map', icon: 'map', pathMatch: 'full' },
    { title: "Login/Register", url: '/login', icon: 'happy', pathMatch: 'full' },
    { title: "Manage Journies", url: '/database', icon: 'trash', pathMatch: 'full' }
  ]
2.	in app.component.html
    
  <ion-app>
    <ion-split-pane>  split-pane displays two components, either side by side or one on top of the othe
      <ion-menu type="overlay"> "backdrop" effect
        <ion-header>
  	<ion-toolbar>
  	  <ion-title>
  	    Menu
  	  </ion-title>
  	</ion-toolbar>
        </ion-header>
        <ion-content>
  	<ion-list>
  	  <ion-menu-toggle auto-hide="false" *ngFor="let p of appMenu">  each element p of appMenu[] declared in app.component.ts
  	    <ion-item [routerDirection]="'root'" [routerLink]="[p.url]">
  	      <ion-icon slot="start" [name]="p.icon"></ion-icon>
  	      <ion-label>{{p.title}} </ion-label>
  	    </ion-item>
  	  </ion-menu-toggle>
  	</ion-list>
        </ion-content>
      </ion-menu>

  <ion-router-outlet main></ion-router-outlet>
</ion-split-pane>
</ion-app>
As when the application starts it automatically goes to home page, as it can be seen from app-routing.module.ts the following code needs to be added to home.page.html
	<ion-header>
	  <ion-toolbar>
	    <ion-buttons slot="start"> shift all buttons to the left
	      <ion-menu-button></ion-menu-button> "hamburger button"
	    </ion-buttons>
	    <ion-title>
	      Going My Way/RideShare
	    </ion-title>
	  </ion-toolbar>
	</ion-header>

**Comment by cormacmchale** [comment]
Essentially the page almost functions as an SPA. With the appMenu being part of the app.component.ts and when you click on the menu Icon you are displayed the app.component.html.. this then allows you to select which page to load into the view.
Browser
![browser](https://user-images.githubusercontent.com/33293951/56744704-ec4d5580-6770-11e9-9cd7-d99a7cfc4332.PNG)
Android:
![android](https://user-images.githubusercontent.com/33293951/56744728-f40cfa00-6770-11e9-9a28-0d04ad42c99a.PNG)

**Comment by cormacmchale** [comment]
The Source Code for the setup 
![Capture](https://user-images.githubusercontent.com/33293951/56744850-2d456a00-6771-11e9-8675-2e377b0fc660.PNG)
![Capture2](https://user-images.githubusercontent.com/33293951/56744857-30405a80-6771-11e9-83be-163d2af8dfcc.PNG)
